import Reach, { useState, useEffect } from 'react';
import Aragorn from '../images/Aragorn.jpg'
import Boromir from '../images/Boromir.jpg'
import Elrond from '../images/Elrond.jpg'
import Faramir from '../images/Faramir.png'
import Frodo from '../images/Frodo.png'
import Galadriel from '../images/Galadriel.jpg'
import Gandalf from '../images/Gandalf.jpg'
import Gimli from '../images/Gimli.png'
import Gollum from '../images/Gollum.png'
import Legolas from '../images/Legolas.jpg'
import Merry from '../images/Merry.jpg'
import Pippin from '../images/Pippin.jpg'
import Sam from '../images/Sam.jpg'
import Saruman from '../images/Saruman.jpg'
import Theoden from '../images/Theoden.jpg'